# -------------------
# Jekyll Config
# --------------------
baseurl: ""
url: "https://garcia57.github.io/my-blog" #https://garcia57.github.io
permalink: pretty
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page/:num"

# Collections
collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:path/

# Pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      permalink: /category/:basename/
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# SCSS
sass:
  style: compact

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml


# -------------------
# Theme Config
# --------------------
title: "Andy's Data Science Blog"
email: "andy.moroni.garcia@gmail.com"
author: "Andy Garcia"
category_dir: 'category'

colors:
  #light-mode colors
  primary_bg: "#EC255A"
  primary_bg_2: "#eed2d9"
  primary_bg_3: "#eed2d9"
  primary_text: "#f9fafb"
  base_bg: "#ffffff"
  base_bg_2: "#ebeef0"
  base_bg_3: "#d6dbe0"
  base_text: "#191a1a"
  base_text_2: "#555555"
  logo_text: "#191a1a"
  menu_text: "#191a1a"

  # dark-mode colors
  primary_bg_dark: "#EC255A"
  primary_bg_2_dark: "#eed2d9"
  primary_bg_3_dark: "#eed2d9"
  primary_text_dark: "#f9fafb"
  base_bg_dark: "#121418"
  base_bg_2_dark: "#1d2026"
  base_bg_3_dark: "#24272d"
  base_text_dark: "#F4F4F5"
  base_text_2_dark: "#D1D5DB"
  logo_text_dark: "#F4F4F5"
  menu_text_dark: "#F4F4F5"

fonts:
  use_google_fonts: false # will use external google_fonts url below
  google_fonts_url: "https://fonts.googleapis.com/css2?&family=Schibsted+Grotesk:wght@400;500&family=Open+Sans:wght@300;400;500;600;700&family=Fira+Mono&display=swap"
  use_self_hosted_fonts: true # font files must be placed in /assets/fonts folder and the @font-face definitions must be added to /assets/css/fonts.css
  heading: "Schibsted Grotesk"
  base: "Open Sans"
  monospace: "Fira Mono"
  logo: "Schibsted Grotesk"

logo:
  logo_text: "Andy Garcia"
  logo_image: assets/images/logo/logo.svg
  logo_image_mobile: assets/images/logo/logo-mobile.svg
  logo_image_invert: assets/images/logo/logo-invert.svg
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.svg
  logo_image_desktop_height: "30px"
  logo_image_desktop_width: "30px"
  logo_image_mobile_height: "28px"
  logo_image_mobile_width: "28px"
  show_logo_image_on_mobile: false
  show_logo_image_on_desktop: false
  show_logo_text_on_mobile: true
  show_logo_text_on_desktop: true

header: 
  fixed: false

open_graph:
  meta_opengraph_type: "website"
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: true 
  show_dark_mode_toggle_in_bottom: false # displays the dark mode toggle switch in the footer and allows the user to manually change the mode
  show_dark_mode_toggle_in_mobile_menu: false # displays the dark mode toggle switch in the footer and allows the user to manually change the mode

cookie_banner:
  enabled: false
  show_manage_cookies_at_bottom: true

analytics:
  disable_analytics_on_localhost: false # prevents polluting analytics data while developing but enabling can be useful
  google_analytics_id: "" # G-XXXXXXXXXX
  gtm_id: "" # GTM-XXXXXXXX
  plausible_data_domain: "" # mywebsite.com
  umami_data_website_id: "" # ddd14336-5fb0-4cdd-8f32-e1bfa906cc2b
  umami_src: "" # https://analytics.eu.umami.is/script.js

#Need to replace the comment functionality here. Disqus and Commento are NOT an option. [Andy]
#Will need to update the "Comments.html" file to include an else if that will trigger the necessary comment pieces
#Will also need a <comment program>.html file that will grap the needed keys from comments.html and use them in its processes
comments:
  commento:
    enabled: false # you must have a commento account and be on the correct domain. does not work locally.
  disqus:
    shortname: "zerostatic" # Your disqus shortcode for example "zerostatic". leave this blank ie "" to disable.


#To activate subscription to an email list, I'd need to include my mailchimp form url below
newsletter:
  mailchimp:
    form_action_url: #"https://zerostatic.us21.list-manage.com/subscribe/post?u=798e19886b83aaab346734382&amp;id=f1c526a772&amp;f_id=0027e3e6f0"
    form_title: "Stay In Touch"

contact_form: 
  use_netlify_form: false
  use_formspree_form: false
  formspree_endpoint: https://formspree.io/f/moqyklqv
  netlify_form_name: "contact"

menu: 
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: true

footer:
  enable_footer: true # show/hide the entire footer
  footer_title: "Andy Garcia's Blog"
  footer_description: "Visit again and learn something new."
  enable_social_media_icons: true
  enable_menu_footer_primary: true
  enable_menu_footer_secondary: false
  enable_menu_footer_tertiary: false
  footer_primary_menu_title: <strong>Links</strong>
  footer_secondary_menu_title: "Menu 2"
  footer_tertiary_menu_title: "Menu 3"

bottom:
  enable_bottom: true # show/hide the entire bottom (below the footer) bundle exec jekyll build
  enable_bottom_menu: true # if enabled, the bottom menu can be edited in `_data/menu.yml` #Jekyll serve
  copyright_text: "" #"© Janus, LLC"
  show_rss_icon: true
